server:
  port: 8000

mybatis-plus:
  mapper-locations: classpath:com/atguigu/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  application:
    name: shop-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.43.160:8848
  rabbitmq:
    host: 192.168.43.160
    port: 5672
    username: admin
    password: 123
  redis:
    host: 192.168.43.160
    port: 6379
    database: 0
    timeout: 1800000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shop_product?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

fastdfs:
  prefix: http://192.168.43.160/
